Arenas:
  MapCycling:
  - arena1
  - arena2
  arena1:
    cuboid:
      min:
        ==: org.bukkit.Location
        world: arena1
        x: -43.0
        y: 69.0
        z: -10.0
        pitch: 0.0
        yaw: 0.0
      max:
        ==: org.bukkit.Location
        world: arena1
        x: 9.0
        y: 94.0
        z: 48.0
        pitch: 0.0
        yaw: 0.0
    Teams:
      Spectator:
        Spawn:
          ==: org.bukkit.Location
          world: arena1
          x: -40.24793566930642
          y: 92.0
          z: 46.087609947191865
          pitch: 31.099737
          yaw: 225.297
      Blue:
        Spawn:
          ==: org.bukkit.Location
          world: arena1
          x: -16.9143953525001
          y: 78.0
          z: 40.92038147287028
          pitch: 0.6589713
          yaw: 179.83801
        Wall:
          min:
            ==: org.bukkit.Location
            world: arena1
            x: -39.0
            y: 77.0
            z: 22.0
            pitch: 0.0
            yaw: 0.0
          max:
            ==: org.bukkit.Location
            world: arena1
            x: 4.0
            y: 79.0
            z: 23.0
            pitch: 0.0
            yaw: 0.0
        Tower:
          '1':
            min:
              ==: org.bukkit.Location
              world: arena1
              x: -35.0
              y: 77.0
              z: 39.0
              pitch: 0.0
              yaw: 0.0
            max:
              ==: org.bukkit.Location
              world: arena1
              x: -32.0
              y: 82.0
              z: 42.0
              pitch: 0.0
              yaw: 0.0
            Middle:
              ==: org.bukkit.Location
              world: arena1
              x: -33.5
              y: 89.5
              z: 40.5
              pitch: 0.0
              yaw: 0.0
          '2':
            min:
              ==: org.bukkit.Location
              world: arena1
              x: -2.0
              y: 77.0
              z: 39.0
              pitch: 0.0
              yaw: 0.0
            max:
              ==: org.bukkit.Location
              world: arena1
              x: 1.0
              y: 82.0
              z: 42.0
              pitch: 0.0
              yaw: 0.0
            Middle:
              ==: org.bukkit.Location
              world: arena1
              x: -0.5
              y: 89.5
              z: 40.5
              pitch: 0.0
              yaw: 0.0
        Area:
          min:
            ==: org.bukkit.Location
            world: arena1
            x: -39.0
            y: 75.0
            z: 24.0
            pitch: 0.0
            yaw: 0.0
          max:
            ==: org.bukkit.Location
            world: arena1
            x: 4.0
            y: 86.0
            z: 44.0
            pitch: 0.0
            yaw: 0.0
        Core:
          min:
            ==: org.bukkit.Location
            world: arena1
            x: -24.0
            y: 74.0
            z: 37.0
            pitch: 0.0
            yaw: 0.0
          max:
            ==: org.bukkit.Location
            world: arena1
            x: -11.0
            y: 82.0
            z: 50.0
            pitch: 0.0
            yaw: 0.0
          Middle:
            ==: org.bukkit.Location
            world: arena1
            x: -17.5
            y: 86.0
            z: 43.5
            pitch: 0.0
            yaw: 0.0
      Red:
        Spawn:
          ==: org.bukkit.Location
          world: arena1
          x: -17.04575402215651
          y: 78.0
          z: -0.8760723804035566
          pitch: -2.240145
          yaw: 359.8169
        Wall:
          min:
            ==: org.bukkit.Location
            world: arena1
            x: -39.0
            y: 77.0
            z: 16.0
            pitch: 0.0
            yaw: 0.0
          max:
            ==: org.bukkit.Location
            world: arena1
            x: 4.0
            y: 79.0
            z: 17.0
            pitch: 0.0
            yaw: 0.0
        Tower:
          '1':
            min:
              ==: org.bukkit.Location
              world: arena1
              x: -2.0
              y: 77.0
              z: -3.0
              pitch: 0.0
              yaw: 0.0
            max:
              ==: org.bukkit.Location
              world: arena1
              x: 1.0
              y: 82.0
              z: 0.0
              pitch: 0.0
              yaw: 0.0
            Middle:
              ==: org.bukkit.Location
              world: arena1
              x: -0.5
              y: 89.5
              z: -1.5
              pitch: 0.0
              yaw: 0.0
          '2':
            min:
              ==: org.bukkit.Location
              world: arena1
              x: -36.0
              y: 77.0
              z: -3.0
              pitch: 0.0
              yaw: 0.0
            max:
              ==: org.bukkit.Location
              world: arena1
              x: -33.0
              y: 82.0
              z: 0.0
              pitch: 0.0
              yaw: 0.0
            Middle:
              ==: org.bukkit.Location
              world: arena1
              x: -34.5
              y: 89.5
              z: -1.5
              pitch: 0.0
              yaw: 0.0
        Area:
          min:
            ==: org.bukkit.Location
            world: arena1
            x: -39.0
            y: 75.0
            z: -5.0
            pitch: 0.0
            yaw: 0.0
          max:
            ==: org.bukkit.Location
            world: arena1
            x: 4.0
            y: 86.0
            z: 15.0
            pitch: 0.0
            yaw: 0.0
        Core:
          min:
            ==: org.bukkit.Location
            world: arena1
            x: -24.0
            y: 74.0
            z: -11.0
            pitch: 0.0
            yaw: 0.0
          max:
            ==: org.bukkit.Location
            world: arena1
            x: -11.0
            y: 81.0
            z: 2.0
            pitch: 0.0
            yaw: 0.0
          Middle:
            ==: org.bukkit.Location
            world: arena1
            x: -17.0
            y: 86.0
            z: -4.0
            pitch: 0.0
            yaw: 0.0
  arena2:
    cuboid:
      min:
        ==: org.bukkit.Location
        world: arena2
        x: -100.0
        y: 115.0
        z: -41.0
        pitch: 0.0
        yaw: 0.0
      max:
        ==: org.bukkit.Location
        world: arena2
        x: -39.0
        y: 185.0
        z: 90.0
        pitch: 0.0
        yaw: 0.0
    Teams:
      Blue:
        Spawn:
          ==: org.bukkit.Location
          world: arena2
          x: -90.54588699776052
          y: 134.5
          z: -31.796951332074833
          pitch: 18.444715
          yaw: 272.91034
        Wall:
          min:
            ==: org.bukkit.Location
            world: arena2
            x: -99.0
            y: 115.0
            z: 12.0
            pitch: 0.0
            yaw: 0.0
          max:
            ==: org.bukkit.Location
            world: arena2
            x: -40.0
            y: 137.0
            z: 14.0
            pitch: 0.0
            yaw: 0.0
        Tower:
          '1':
            min:
              ==: org.bukkit.Location
              world: arena2
              x: -62.0
              y: 134.0
              z: -37.0
              pitch: 0.0
              yaw: 0.0
            max:
              ==: org.bukkit.Location
              world: arena2
              x: -44.0
              y: 162.0
              z: -22.0
              pitch: 0.0
              yaw: 0.0
            Middle:
              ==: org.bukkit.Location
              world: arena2
              x: -53.0
              y: 158.0
              z: -29.5
              pitch: 0.0
              yaw: 0.0
          '2':
            min:
              ==: org.bukkit.Location
              world: arena2
              x: -99.0
              y: 142.0
              z: -21.0
              pitch: 0.0
              yaw: 0.0
            max:
              ==: org.bukkit.Location
              world: arena2
              x: -81.0
              y: 162.0
              z: -2.0
              pitch: 0.0
              yaw: 0.0
            Middle:
              ==: org.bukkit.Location
              world: arena2
              x: -90.0
              y: 162.0
              z: -11.5
              pitch: 0.0
              yaw: 0.0
        Area:
          min:
            ==: org.bukkit.Location
            world: arena2
            x: -99.0
            y: 115.0
            z: -40.0
            pitch: 0.0
            yaw: 0.0
          max:
            ==: org.bukkit.Location
            world: arena2
            x: -40.0
            y: 200.0
            z: 11.0
            pitch: 0.0
            yaw: 0.0
        Core:
          min:
            ==: org.bukkit.Location
            world: arena2
            x: -76.0
            y: 129.0
            z: -15.0
            pitch: 0.0
            yaw: 0.0
          max:
            ==: org.bukkit.Location
            world: arena2
            x: -64.0
            y: 140.0
            z: -3.0
            pitch: 0.0
            yaw: 0.0
          Middle:
            ==: org.bukkit.Location
            world: arena2
            x: -70.0
            y: 142.5
            z: -9.0
            pitch: 0.0
            yaw: 0.0
      Spectator:
        Spawn:
          ==: org.bukkit.Location
          world: arena2
          x: -15.46092321646505
          y: 154.63120114892126
          z: 24.481209994235407
          pitch: 34.126213
          yaw: 271.32974
      Red:
        Spawn:
          ==: org.bukkit.Location
          world: arena2
          x: -47.15013585453323
          y: 134.5
          z: 81.61752520079548
          pitch: -4.6165233
          yaw: 91.4711
        Wall:
          min:
            ==: org.bukkit.Location
            world: arena2
            x: -99.0
            y: 115.0
            z: 35.0
            pitch: 0.0
            yaw: 0.0
          max:
            ==: org.bukkit.Location
            world: arena2
            x: -40.0
            y: 137.0
            z: 37.0
            pitch: 0.0
            yaw: 0.0
        Tower:
          '1':
            min:
              ==: org.bukkit.Location
              world: arena2
              x: -93.0
              y: 134.0
              z: 71.0
              pitch: 0.0
              yaw: 0.0
            max:
              ==: org.bukkit.Location
              world: arena2
              x: -75.0
              y: 158.0
              z: 87.0
              pitch: 0.0
              yaw: 0.0
            Middle:
              ==: org.bukkit.Location
              world: arena2
              x: -84.0
              y: 156.0
              z: 79.0
              pitch: 0.0
              yaw: 0.0
          '2':
            min:
              ==: org.bukkit.Location
              world: arena2
              x: -59.0
              y: 144.0
              z: 51.0
              pitch: 0.0
              yaw: 0.0
            max:
              ==: org.bukkit.Location
              world: arena2
              x: -39.0
              y: 164.0
              z: 71.0
              pitch: 0.0
              yaw: 0.0
            Middle:
              ==: org.bukkit.Location
              world: arena2
              x: -49.0
              y: 164.0
              z: 61.0
              pitch: 0.0
              yaw: 0.0
        Area:
          min:
            ==: org.bukkit.Location
            world: arena2
            x: -99.0
            y: 115.0
            z: 38.0
            pitch: 0.0
            yaw: 0.0
          max:
            ==: org.bukkit.Location
            world: arena2
            x: -40.0
            y: 200.0
            z: 89.0
            pitch: 0.0
            yaw: 0.0
        Core:
          min:
            ==: org.bukkit.Location
            world: arena2
            x: -76.0
            y: 129.0
            z: 52.0
            pitch: 0.0
            yaw: 0.0
          max:
            ==: org.bukkit.Location
            world: arena2
            x: -64.0
            y: 140.0
            z: 64.0
            pitch: 0.0
            yaw: 0.0
          Middle:
            ==: org.bukkit.Location
            world: arena2
            x: -70.0
            y: 142.5
            z: 58.0
            pitch: 0.0
            yaw: 0.0
